In [10]:
import numpy as np
np.__version__


'1.19.2'

In [11]:
x=4
x?

In [12]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
type(L[0])

int

In [14]:
L2 = [str(c) for c in L]
L2


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
type(L2[0])

str

In [16]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [17]:
import array
L = list(range(10))
A = array.array('i', L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
import numpy as np

In [19]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [20]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [21]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
np.random.random((3,3))

array([[0.83419203, 0.9674452 , 0.31135321],
       [0.91078374, 0.52305723, 0.82320668],
       [0.2439997 , 0.4635985 , 0.76383203]])

In [24]:
np.random.normal(0,1,(3,3))

array([[-0.78357766, -0.38130037,  2.5419782 ],
       [-1.12888804, -2.21421697,  0.15833405],
       [ 0.68359482,  0.46438575,  0.52066319]])

In [25]:
np.random.randint(0,10,(3,3))

array([[4, 0, 0],
       [6, 0, 1],
       [6, 6, 5]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.empty(3)

array([1., 1., 1.])

In [28]:
np.random.seed(0)

In [29]:
x1 = np.random.randint(10, size=10)
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))

In [30]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [31]:
print("dtype:", x3.dtype)

dtype: int32


In [32]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [33]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [34]:
x1[4]

7

In [35]:
x1[-3]

5

In [36]:
x2

array([[7, 6, 8, 8],
       [1, 6, 7, 7],
       [8, 1, 5, 9]])

In [37]:
x2[1,1]=17

In [38]:
x2

array([[ 7,  6,  8,  8],
       [ 1, 17,  7,  7],
       [ 8,  1,  5,  9]])

In [39]:
x2[2,-2]

5

In [40]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [41]:
x1[:3]

array([5, 0, 3])

In [42]:
x1[3:]

array([3, 7, 9, 3, 5, 2, 4])

In [43]:
x1[2:5]

array([3, 3, 7])

In [44]:
x1[::2]

array([5, 3, 7, 3, 2])

In [45]:
x1[2::3]

array([3, 9, 2])

In [46]:
x1[6::-2]

array([3, 7, 3, 5])

In [47]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [48]:
x2

array([[ 7,  6,  8,  8],
       [ 1, 17,  7,  7],
       [ 8,  1,  5,  9]])

In [49]:
x2[:2,:3]

array([[ 7,  6,  8],
       [ 1, 17,  7]])

In [50]:
x2[:2,::2]

array([[7, 8],
       [1, 7]])

In [51]:
x2[::-1,::-1]

array([[ 9,  5,  1,  8],
       [ 7,  7, 17,  1],
       [ 8,  8,  6,  7]])

In [52]:
print(x2[:,0])

[7 1 8]


In [53]:
print(x2[0,:])

[7 6 8 8]


In [54]:
x2

array([[ 7,  6,  8,  8],
       [ 1, 17,  7,  7],
       [ 8,  1,  5,  9]])

In [55]:
print(x2[0])

[7 6 8 8]


In [56]:
x2sub=x2[:2,:2]

In [57]:
x2sub

array([[ 7,  6],
       [ 1, 17]])

In [58]:
x2sub[0,0]=100

In [59]:
x2

array([[100,   6,   8,   8],
       [  1,  17,   7,   7],
       [  8,   1,   5,   9]])

# Creating copies of arrays

In [61]:
x2

array([[100,   6,   8,   8],
       [  1,  17,   7,   7],
       [  8,   1,   5,   9]])

In [65]:
x2subcopy=x2[:2,:2].copy()

In [67]:
x2subcopy

array([[100,   6],
       [  1,  17]])

In [68]:
x2

array([[100,   6,   8,   8],
       [  1,  17,   7,   7],
       [  8,   1,   5,   9]])

# Reshaping of Arrays

In [70]:
x=np.array([4,5,6])
x

array([4, 5, 6])

In [72]:
x.reshape((1,3))

array([[4, 5, 6]])

In [73]:
x[np.newaxis,:]

array([[4, 5, 6]])

In [75]:
x.reshape((3,1))

array([[4],
       [5],
       [6]])

# Concatenation and Splitting

In [76]:
x = np.array([5,6,7])
y = np.array([8,9,8])
np.concatenate([x, y])

array([5, 6, 7, 8, 9, 8])

In [78]:
matriz = np.array([[4, 4, 5],
[8, 8,9]])
np.concatenate([matriz,matriz])

array([[4, 4, 5],
       [8, 8, 9],
       [4, 4, 5],
       [8, 8, 9]])

In [79]:
np.concatenate([matriz, matriz], axis=1)

array([[4, 4, 5, 4, 4, 5],
       [8, 8, 9, 8, 8, 9]])

In [85]:
matriz2 = np.array([1, 1, 1])

In [86]:
np.vstack([matriz,matriz2])

array([[4, 4, 5],
       [8, 8, 9],
       [1, 1, 1]])

In [93]:
matriz


array([[4, 4, 5],
       [8, 8, 9]])

In [97]:
matriz3 = np.array([[0],[0]])

In [98]:
np.hstack([matriz,matriz3])

array([[4, 4, 5, 0],
       [8, 8, 9, 0]])

# Splitting arrays

In [101]:
t= [1, 1, 1, 2, 2, 3, 3, 3]
t1, t2, t3 = np.split(t, [3, 5])
print(t1, t2, t3)

[1 1 1] [2 2] [3 3 3]


In [104]:
grid = np.arange(25).reshape((5, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
upper, lower = np.vsplit(grid, [3])
print(upper)
print(lower)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]]


In [106]:
left, right = np.hsplit(grid, [3])
print(left)
print(right)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]
 [20 21 22]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]
