In [3]:
import numpy as np
numpy.__version__


'1.20.1'

In [4]:
x=4
x?

In [5]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L[0])

int

In [7]:
L2 = [str(c) for c in L]
L2


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

In [9]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [10]:
import array
L = list(range(10))
A = array.array('i', L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
import numpy as np

In [12]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [13]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
np.random.random((3,3))

array([[0.89621258, 0.41794126, 0.81056786],
       [0.6461304 , 0.27587294, 0.23434632],
       [0.97798916, 0.41772819, 0.2520293 ]])

In [18]:
np.random.normal(0,1,(3,3))

array([[-1.11609192,  0.2921445 , -1.76963873],
       [-0.14533056, -1.08200143, -0.85475329],
       [ 1.7487965 , -0.03982673, -1.06402394]])

In [20]:
np.random.randint(0,10,(3,3))

array([[9, 6, 5],
       [5, 7, 1],
       [6, 0, 3]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty(3)

array([1., 1., 1.])

In [23]:
np.random.seed(0)

In [55]:
x1 = np.random.randint(10, size=10)
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))

In [30]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [31]:
print("dtype:", x3.dtype)

dtype: int32


In [32]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [34]:
x1

array([1, 1, 0, 3, 8, 8])

In [35]:
x1[4]

8

In [36]:
x1[-3]

3

In [37]:
x2

array([[4, 4, 0, 9],
       [3, 7, 3, 2],
       [1, 1, 2, 1]])

In [38]:
x2[1,1]=17

In [39]:
x2

array([[ 4,  4,  0,  9],
       [ 3, 17,  3,  2],
       [ 1,  1,  2,  1]])

In [45]:
x2[2,-2]

2

In [46]:
x1

array([1, 1, 0, 3, 8, 8])

In [47]:
x1[:3]

array([1, 1, 0])

In [49]:
x1[3:]

array([3, 8, 8])

In [50]:
x1[2:5]

array([0, 3, 8])

In [51]:
x1[::2]

array([1, 0, 8])

In [52]:
x1[2::3]

array([0, 8])

In [57]:
x1[6::-2]

array([3, 4, 4, 8])

In [56]:
x1

array([8, 5, 4, 7, 4, 1, 3, 3, 9, 2])

In [58]:
x2

array([[5, 2, 3, 5],
       [7, 2, 7, 1],
       [6, 5, 0, 0]])

In [60]:
x2[:2,:3]

array([[5, 2, 3],
       [7, 2, 7]])

In [61]:
x2[:2,::2]

array([[5, 3],
       [7, 7]])

In [63]:
x2[::-1,::-1]

array([[0, 0, 5, 6],
       [1, 7, 2, 7],
       [5, 3, 2, 5]])

In [64]:
print(x2[:,0])

[5 7 6]


In [66]:
print(x2[0,:])

[5 2 3 5]


In [67]:
x2

array([[5, 2, 3, 5],
       [7, 2, 7, 1],
       [6, 5, 0, 0]])

In [68]:
print(x2[0])

[5 2 3 5]


In [72]:
x2sub=x2[:2,:2]

In [73]:
x2sub

array([[5, 2],
       [7, 2]])

In [74]:
x2sub[0,0]=100

In [78]:
x2

array([[100,   2,   3,   5],
       [  7,   2,   7,   1],
       [  6,   5, 100,   0]])