In [2]:
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

5.04 s ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [7]:
%timeit (1.0 / big_array)

6.03 ms ± 67.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [10]:
np.arange(5)/np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [11]:
x = np.arange(9).reshape((3, 3))

In [14]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

## 

In [15]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]


In [17]:
#puede ser pregunta de examen. Generar este array y luego cambiar el signo o aplicarle una funcion y medir el tiempo de ejecucion

In [18]:
big_array = np.random.randint(-100, 0, size=100)

[ -66  -21  -76  -52   -9  -82  -51  -30  -49  -83   -6  -73  -62  -69
  -48  -36  -91  -22   -7  -71  -33  -73  -31   -9  -32  -49 -100  -55
  -46  -30  -93  -83  -34  -66  -68  -17  -70   -5  -93  -85  -18   -3
  -57  -16  -92  -61 -100  -61  -49  -54  -67  -89  -18  -76  -24  -82
  -98   -2  -85  -20   -3  -47  -25  -16  -77  -69  -48  -49  -32  -94
  -52  -23  -12  -53  -41  -29   -6  -51  -22  -64  -45  -68  -75  -74
  -69  -90  -33  -97  -99  -98  -97  -25  -63  -34  -91   -7  -59  -87
  -40  -85]


In [19]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [21]:
x=np.arange(1,6)

In [22]:
x

array([1, 2, 3, 4, 5])

In [24]:
np.multiply.reduce(x)

120

In [27]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])